### PR TITLE
Charlie

### PR DESCRIPTION
**Pull request by charlie-becker**
Added feature to include height interpolated data (constrained to the number of levels the ML model uses) using `{variable}_h` as the variable name. The flag is in the config as `add_interp_data:`

Also includes a variable `isobaricInhPa_h` as the pressure levels at the height levels to make plotting skew-Ts in pressure coordinates (in height levels) possible. Also includes a coordinate variable `heightAboveGround`.

### CODE REVIEW

**Comment by charlie-becker** [comment]
Added feature to subset by extent (via config).

**Comment by ThomasMGeo** [comment]
Is the goal to merge this before your leave @charlie-becker ?

**Comment by charlie-becker** [comment]
@ThomasMGeo Yeah, this should be merged before I leave. I do not plan to add anything else to unless requested. 

I would like to merge by Wednesday of next week, if possible.

**Comment by ThomasMGeo** [comment]
This looks good to me!

**Pull request merged**
