### PR TITLE
Partial thickness baseline

### PR DESCRIPTION
**Pull request by djgagne**
I have added code for Bhupal's algorithm to run in scikit-learn style or in a function that should run over the full grid for a single RAP valid date and time.

### CODE REVIEW

**Comment by djgagne** [comment]
Can I get a quick review from @ggantos or @charlie-becker ?

**Review by charlie-becker — CHANGES_REQUESTED** [review]
New interpolation functions and ptype prediction with Bhupal's method for RAP look good to me. However, I think I found some issues with the base implementation of the algorithm.
https://github.com/ai2es/ptype-physical/blob/f1d85ced61ca1a12eb7bd9aa1651d2421f258078/ptype/baselines.py#L87
```
    if surface_pressure_hPa > 1000:
        if precip_type[1] == 0.5 and precip_type[2] == 0.5 and temperature_surface < -1:
            precip_type[2] = 0.25
            precip_type[3] = 0.75
        if precip_type[0] == 1 and temperature_surface < -1:
            precip_type[0] = 0.25
            precip_type[3] = 0.75
        if thickness_850_700_m > 1600 and thickness_1000_850_m > 1325:
            precip_type[:] = 0
            precip_type[0] = 1
    return precip_type.reshape(1, -1)
```
In the first nested `if` statement you check for a 0.50 / 0.50 probability split which will never happen due to the arbitrary choice of splitting mixed p-types as 0.25 / 0.75. You could either change all mixed types to 0.5 / 0.5 or change the conditional to `> 0` for both p-types that would support any mixed probability distribution. The assigned ptype also appears to be incorrect for this conditional - it should be [1] and [3] (snow/frz), not [2] and [3] (sleet / frz).

There also seems to be the missing conditional for > than 1000 hPa and ptype is mixed rain / freezing rain, and surface temp < -1, ptype -->  freezing rain / snow. This should be the same as the above referenced line but with mixed freezing rain / rain instead of mixed sleet / snow.

**Comment by djgagne** [comment]
I fixed the conditional and merged in other changes from main.

**Comment by ggantos** [comment]
Looks good to me!

**Pull request merged**
